# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/CMPE_220_2025

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/CMPE_220_2025/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/CMPE_220_2025/build/CMakeFiles /mnt/c/CMPE_220_2025/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/CMPE_220_2025/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cpu

# Build rule for target.
cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cpu
.PHONY : cpu

# fast build rule for target.
cpu/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu.dir/build.make CMakeFiles/cpu.dir/build
.PHONY : cpu/fast

#=============================================================================
# Target rules for targets named emulator

# Build rule for target.
emulator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 emulator
.PHONY : emulator

# fast build rule for target.
emulator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/emulator.dir/build.make CMakeFiles/emulator.dir/build
.PHONY : emulator/fast

#=============================================================================
# Target rules for targets named assembler

# Build rule for target.
assembler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 assembler
.PHONY : assembler

# fast build rule for target.
assembler/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler.dir/build.make CMakeFiles/assembler.dir/build
.PHONY : assembler/fast

alu/alu.o: alu/alu.cpp.o
.PHONY : alu/alu.o

# target to build an object file
alu/alu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu.dir/build.make CMakeFiles/cpu.dir/alu/alu.cpp.o
.PHONY : alu/alu.cpp.o

alu/alu.i: alu/alu.cpp.i
.PHONY : alu/alu.i

# target to preprocess a source file
alu/alu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu.dir/build.make CMakeFiles/cpu.dir/alu/alu.cpp.i
.PHONY : alu/alu.cpp.i

alu/alu.s: alu/alu.cpp.s
.PHONY : alu/alu.s

# target to generate assembly for a file
alu/alu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu.dir/build.make CMakeFiles/cpu.dir/alu/alu.cpp.s
.PHONY : alu/alu.cpp.s

assembler/assembler.o: assembler/assembler.cpp.o
.PHONY : assembler/assembler.o

# target to build an object file
assembler/assembler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler.dir/build.make CMakeFiles/assembler.dir/assembler/assembler.cpp.o
.PHONY : assembler/assembler.cpp.o

assembler/assembler.i: assembler/assembler.cpp.i
.PHONY : assembler/assembler.i

# target to preprocess a source file
assembler/assembler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler.dir/build.make CMakeFiles/assembler.dir/assembler/assembler.cpp.i
.PHONY : assembler/assembler.cpp.i

assembler/assembler.s: assembler/assembler.cpp.s
.PHONY : assembler/assembler.s

# target to generate assembly for a file
assembler/assembler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assembler.dir/build.make CMakeFiles/assembler.dir/assembler/assembler.cpp.s
.PHONY : assembler/assembler.cpp.s

control/control.o: control/control.cpp.o
.PHONY : control/control.o

# target to build an object file
control/control.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu.dir/build.make CMakeFiles/cpu.dir/control/control.cpp.o
.PHONY : control/control.cpp.o

control/control.i: control/control.cpp.i
.PHONY : control/control.i

# target to preprocess a source file
control/control.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu.dir/build.make CMakeFiles/cpu.dir/control/control.cpp.i
.PHONY : control/control.cpp.i

control/control.s: control/control.cpp.s
.PHONY : control/control.s

# target to generate assembly for a file
control/control.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu.dir/build.make CMakeFiles/cpu.dir/control/control.cpp.s
.PHONY : control/control.cpp.s

cpu/cpu.o: cpu/cpu.cpp.o
.PHONY : cpu/cpu.o

# target to build an object file
cpu/cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu.dir/build.make CMakeFiles/cpu.dir/cpu/cpu.cpp.o
.PHONY : cpu/cpu.cpp.o

cpu/cpu.i: cpu/cpu.cpp.i
.PHONY : cpu/cpu.i

# target to preprocess a source file
cpu/cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu.dir/build.make CMakeFiles/cpu.dir/cpu/cpu.cpp.i
.PHONY : cpu/cpu.cpp.i

cpu/cpu.s: cpu/cpu.cpp.s
.PHONY : cpu/cpu.s

# target to generate assembly for a file
cpu/cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu.dir/build.make CMakeFiles/cpu.dir/cpu/cpu.cpp.s
.PHONY : cpu/cpu.cpp.s

cpu/registers.o: cpu/registers.cpp.o
.PHONY : cpu/registers.o

# target to build an object file
cpu/registers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu.dir/build.make CMakeFiles/cpu.dir/cpu/registers.cpp.o
.PHONY : cpu/registers.cpp.o

cpu/registers.i: cpu/registers.cpp.i
.PHONY : cpu/registers.i

# target to preprocess a source file
cpu/registers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu.dir/build.make CMakeFiles/cpu.dir/cpu/registers.cpp.i
.PHONY : cpu/registers.cpp.i

cpu/registers.s: cpu/registers.cpp.s
.PHONY : cpu/registers.s

# target to generate assembly for a file
cpu/registers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu.dir/build.make CMakeFiles/cpu.dir/cpu/registers.cpp.s
.PHONY : cpu/registers.cpp.s

emulator/main.o: emulator/main.cpp.o
.PHONY : emulator/main.o

# target to build an object file
emulator/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/emulator.dir/build.make CMakeFiles/emulator.dir/emulator/main.cpp.o
.PHONY : emulator/main.cpp.o

emulator/main.i: emulator/main.cpp.i
.PHONY : emulator/main.i

# target to preprocess a source file
emulator/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/emulator.dir/build.make CMakeFiles/emulator.dir/emulator/main.cpp.i
.PHONY : emulator/main.cpp.i

emulator/main.s: emulator/main.cpp.s
.PHONY : emulator/main.s

# target to generate assembly for a file
emulator/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/emulator.dir/build.make CMakeFiles/emulator.dir/emulator/main.cpp.s
.PHONY : emulator/main.cpp.s

memory/memory.o: memory/memory.cpp.o
.PHONY : memory/memory.o

# target to build an object file
memory/memory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu.dir/build.make CMakeFiles/cpu.dir/memory/memory.cpp.o
.PHONY : memory/memory.cpp.o

memory/memory.i: memory/memory.cpp.i
.PHONY : memory/memory.i

# target to preprocess a source file
memory/memory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu.dir/build.make CMakeFiles/cpu.dir/memory/memory.cpp.i
.PHONY : memory/memory.cpp.i

memory/memory.s: memory/memory.cpp.s
.PHONY : memory/memory.s

# target to generate assembly for a file
memory/memory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu.dir/build.make CMakeFiles/cpu.dir/memory/memory.cpp.s
.PHONY : memory/memory.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... assembler"
	@echo "... cpu"
	@echo "... emulator"
	@echo "... alu/alu.o"
	@echo "... alu/alu.i"
	@echo "... alu/alu.s"
	@echo "... assembler/assembler.o"
	@echo "... assembler/assembler.i"
	@echo "... assembler/assembler.s"
	@echo "... control/control.o"
	@echo "... control/control.i"
	@echo "... control/control.s"
	@echo "... cpu/cpu.o"
	@echo "... cpu/cpu.i"
	@echo "... cpu/cpu.s"
	@echo "... cpu/registers.o"
	@echo "... cpu/registers.i"
	@echo "... cpu/registers.s"
	@echo "... emulator/main.o"
	@echo "... emulator/main.i"
	@echo "... emulator/main.s"
	@echo "... memory/memory.o"
	@echo "... memory/memory.i"
	@echo "... memory/memory.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

